<?php
$conn = new mysqli("localhost", "root", "", "report");

$result = mysqli_query($conn, "SELECT * FROM `smrf`");

$num= mysqli_num_rows($result);
echo "total rows:$num";
echo"<br> <br>";

if($num>0)
{
$b_smrf=array();
while($row = mysqli_fetch_assoc($result))
{
    echo "\n";
    // loop through each column
    foreach($row as $key => $value){
        if($key=="prior-intervention-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["prior-intervention-presence"]=0;
            }else{
                $b_smrf["prior-intervention-presence"]=0;
            }
        }
        if($key=="prior-intervention-condition")
        {
           if(strtolower($value=='poor'))
           {
               $b_smrf["prior-intervention-condition"]=8;
           }
           elseif(strtolower($value=='average'))
           {
               $b_smrf["prior-intervention-condition"]=4;
           }
           elseif(strtolower($value=='good'))
           {
               $b_smrf["prior-intervention-condition"]=0;
           }
        } 

        if($key=="presenceofexpansionjoint")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["presenceofexpansionjoint"]=0;
            }else{
                $b_smrf["presenceofexpansionjoint"]=0;
            }
        }
        if($key=="expansionjoint-condition")
        {
           if(strtolower($value=='poor'))
           {
               $b_smrf["expansionjoint-condition"]=4;
           }
           elseif(strtolower($value=='average'))
           {
               $b_smrf["expansionjoint-condition"]=2;
           }
           elseif(strtolower($value=='good'))
           {
               $b_smrf["expansionjoint-condition"]=0;
           }
        } 
        if($key=="foundationsettlement-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["foundationsettlement-presence"]=0;
            }else{
                $b_smrf["foundationsettlement-presence"]=0;
            }
        }
        if($key=="foundationsettlement-condition")
        {
           if(strtolower($value=='poor'))
           {
               $b_smrf["foundationsettlement-condition"]=8;
           }
           elseif(strtolower($value=='average'))
           {
               $b_smrf["foundationsettlement-condition"]=4;
           }
           elseif(strtolower($value=='good'))
           {
               $b_smrf["foundationsettlement-condition"]=0;
           }
        } 
        if($key=="reentrantcorner-present")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["reentrantcorner-present"]=8;
            }else{
                $b_smrf["reentrantcorner-present"]=0;
            }
        }
        if($key=="nonparralellsystem-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["nonparralellsystem-presence"]=8;
            }else{
                $b_smrf["nonparralellsystem-presence"]=0;
            }
        }
        if($key=="outofplaneoffset-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["outofplaneoffset-presence"]=8;
            }else{
                $b_smrf["outofplaneoffset-presence"]=0;
            }
        }
        if($key=="torsionirregularity-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["torsionirregularity-presence"]=16;
            }else{
                $b_smrf["torsionirregularity-presence"]=0;
            }
        }
        if($key=="slabopening-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["slabopening-presence"]=0;
            }else{
                $b_smrf["slabopening-presence"]=8;
            }
        }
        if($key=="presenceofcantilever-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["presenceofcantilever-presence"]=4;
            }else{
                $b_smrf["presenceofcantilever-presence"]=0;
            }
        }
        if($key=="visibledeflectionofbeams-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["visibledeflectionofbeams-presence"]=4;
            }else{
                $b_smrf["visibledeflectionofbeams-presence"]=0;
            }
        }
        if($key=="visibledeflectionofslab-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["visibledeflectionofslab-presence"]=4;
            }else{
                $b_smrf["visibledeflectionofslab-presence"]=0;
            }
        }
        if($key=="diaphragmcontiuity-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["diaphragmcontiuity-presence"]=8;
            }else{
                $b_smrf["diaphragmcontiuity-presence"]=0;
            }
        }
        if($key=="setback-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["setback-presence"]=0;
            }else{
                $b_smrf["setback-presence"]=0;
            }
        }
        // set back present
        // if($key=="")
        // {
        //    if(strtolower($value=='outward'))
        //    {
        //        $b_smrf[""]=16;
        //    }
        //    elseif(strtolower($value=='inward'))
        //    {
        //        $b_smrf[""]=8;
        //    }
        //    elseif(strtolower($value=='in-plane'))
        //    {
        //        $b_smrf[""]=4;
        //    }
        // } 

        if($key=="completeloadpath-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["completeloadpath-presence"]=0;
            }else{
                $b_smrf["completeloadpath-presence"]=4;
            }
        }
        if($key=="redundancy-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["redundancy-presence"]=0;
            }else{
                $b_smrf["redundancy-presence"]=4;
            }
        }
        if($key=="weakstory-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["weakstory-presence"]=16;
            }else{
                $b_smrf["weakstory-presence"]=0;
            }
        }
        if($key=="softstorypresence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["softstorypresence"]=16;
            }else{
                $b_smrf["softstorypresence"]=0;
            }
        }
        if($key=="softstorypresence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["softstorypresence"]=4;
            }else{
                $b_smrf["softstorypresence"]=0;
            }
        }
        if($key=="pounding-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["pounding-presence"]=0;
            }else{
                $b_smrf["pounding-presence"]=0;
            }
        }
        // pounding yes condition table (db table)
        if($key=="strongcolumnweak-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["strongcolumnweak-presence"]=0;
            }else{
                $b_smrf["strongcolumnweak-presence"]=8;
            }
        }
        if($key=="massirregularity-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["massirregularity-presence"]=4;
            }else{
                $b_smrf["massirregularity-presence"]=0;
            }
        }
        
        if($key=="transfertoshearwall-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["transfertoshearwall-presence"]=0;
            }else{
                $b_smrf["transfertoshearwall-presence"]=4;
            }
        }
        if($key=="noflatslabframes-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["noflatslabframes-presence"]=0;
            }else{
                $b_smrf["noflatslabframes-presence"]=8;
            }
        }
        if($key=="overtuningofshearwall-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["overtuningofshearwall-presence"]=4;
            }else{
                $b_smrf["overtuningofshearwall-presence"]=0;
            }
        }
        if($key=="wallthickness-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["wallthickness-presence"]=0;
            }else{
                $b_smrf["wallthickness-presence"]=4;
            }
        }
        
        if($key=="short/captivecolumn-presencr")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["short/captivecolumn-presencr"]=8;
            }else{
                $b_smrf["short/captivecolumn-presencr"]=0;
            }
        }
        
        if($key=="lateralcolumndrift-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["lateralcolumndrift-presence"]=4;
            }else{
                $b_smrf["lateralcolumndrift-presence"]=0;
            }
        }
        if($key=="openingadjtoshearwall-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["openingadjtoshearwall-presence"]=4;
            }else{
                $b_smrf["openingadjtoshearwall-presence"]=0;
            }
        }
        // confirm db column is of Beam bar splices compliant 
        if($key=="beambarsplices-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["beambarsplices-presence"]=0;
            }else{
                $b_smrf["beambarsplices-presence"]=4;
            }
        }
        // confirm db column is of Beam-Column Joint eccentricity not exist 
        if($key=="jointeccentricity-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["jointeccentricity-presence"]=0;
            }else{
                $b_smrf["jointeccentricity-presence"]=4;
            }
        }
        // confirm db column is of Stirrups/Hoops and Tie hooks are compliant
        if($key=="stirrupandtiehook-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["stirrupandtiehook-presence"]=0;
            }else{
                $b_smrf["stirrupandtiehook-presence"]=4;
            }
        }
        // confirm if this db coulmn is of Reinforcement requirement compliant at opening in Diaphragm
        if($key=="diaphragmreinforcement-presence")
        {
            if(strtolower($value)=="yes"){
                $b_smrf["diaphragmreinforcement-presence"]=0;
            }else{
                $b_smrf["diaphragmreinforcement-presence"]=4;
            }
        }
        // Typical Beam Deterioation
        if($key=="typicalbeamdetercracks-condtion")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalbeamdetercracks-condtion"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalbeamdetercracks-condtion"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalbeamdetercracks-condtion"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalbeamdetercracks-condtion"]=0;
           }
        } 
        if($key=="typicalbeamdeterscaling-condtion")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalbeamdeterscaling-condtion"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalbeamdeterscaling-condtion"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalbeamdeterscaling-condtion"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalbeamdeterscaling-condtion"]=0;
           }
        } 
        if($key=="typicalbeamdeterr/fexp-condtion")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalbeamdeterr/fexp-condtion"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalbeamdeterr/fexp-condtion"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalbeamdeterr/fexp-condtion"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalbeamdeterr/fexp-condtion"]=0;
           }
        } 
        if($key=="typicalbeamdeterr/fcorro-condtion")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalbeamdeterr/fcorro-condtion"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalbeamdeterr/fcorro-condtion"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalbeamdeterr/fcorro-condtion"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalbeamdeterr/fcorro-condtion"]=0;
           }
        } 
        if($key=="typicalbeamdeterhoneycomb-condtion")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalbeamdeterhoneycomb-condtion"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalbeamdeterhoneycomb-condtion"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalbeamdeterhoneycomb-condtion"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalbeamdeterhoneycomb-condtion"]=0;
           }
        } 
        // Typical Beam Deterioation only for steel
        if($key=="steeltypicalbeamdeterrusting-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalbeamdeterrusting-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalbeamdeterrusting-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalbeamdeterrusting-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalbeamdeterrusting-condition"]=0;
           }
        } 
        if($key=="steeltypicalbeamdeterflaking-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalbeamdeterflaking-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalbeamdeterflaking-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalbeamdeterflaking-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalbeamdeterflaking-condition"]=0;
           }
        }  if($key=="steeltypicalbeamdeteryeilding-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalbeamdeteryeilding-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalbeamdeteryeilding-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalbeamdeteryeilding-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalbeamdeteryeilding-condition"]=0;
           }
        }  if($key=="steeltypicalbeamdeterbuckling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalbeamdeterbuckling-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalbeamdeterbuckling-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalbeamdeterbuckling-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalbeamdeterbuckling-condition"]=0;
           }
        } 
        // Typical Column Deterioation
        if($key=="typicalcolumndetercracks-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcolumndetercracks-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcolumndetercracks-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcolumndetercracks-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcolumndetercracks-condition"]=0;
           }
        } 
        if($key=="typicalcolumndeterscaling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcolumndeterscaling-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcolumndeterscaling-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcolumndeterscaling-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcolumndeterscaling-condition"]=0;
           }
        } 
        if($key=="typicalcolumndeterr/fexp-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcolumndeterr/fexp-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcolumndeterr/fexp-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcolumndeterr/fexp-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcolumndeterr/fexp-condition"]=0;
           }
        } 
        if($key=="typicalcolumndeterr/fcorro-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcolumndeterr/fcorro-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcolumndeterr/fcorro-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcolumndeterr/fcorro-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcolumndeterr/fcorro-condition"]=0;
           }
        } 
        if($key=="typicalcolumndeterhoneycomb-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcolumndeterhoneycomb-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcolumndeterhoneycomb-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcolumndeterhoneycomb-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcolumndeterhoneycomb-condition"]=0;
           }
        } 
        // Typical Column Deterioation only for steel
        if($key=="steeltypicalcolumndeterrusting-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalcolumndeterrusting-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalcolumndeterrusting-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalcolumndeterrusting-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalcolumndeterrusting-condition"]=0;
           }
        } 
        if($key=="steeltypicalcolumndeterflaking-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalcolumndeterflaking-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalcolumndeterflaking-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalcolumndeterflaking-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalcolumndeterflaking-condition"]=0;
           }
        }
        if($key=="steeltypicalcolumndeteryielding-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalcolumndeteryielding-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalcolumndeteryielding-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalcolumndeteryielding-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalcolumndeteryielding-condition"]=0;
           }
        } 
        if($key=="steeltypicalcolumndeterbuckling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalcolumndeterbuckling-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalcolumndeterbuckling-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalcolumndeterbuckling-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalcolumndeterbuckling-condition"]=0;
           }
        }  
        // typical Slab Deterioation
        if($key=="typicalslabdetercracks-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalslabdetercracks-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalslabdetercracks-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalslabdetercracks-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalslabdetercracks-condition"]=0;
           }
        } 
        if($key=="typicalslabdeterscaling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalslabdeterscaling-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalslabdeterscaling-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalslabdeterscaling-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalslabdeterscaling-condition"]=0;
           }
        } 
        if($key=="typicalslabdeterr/fexp-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalslabdeterr/fexp-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalslabdeterr/fexp-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalslabdeterr/fexp-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalslabdeterr/fexp-condition"]=0;
           }
        } 
        if($key=="typicalslabdeterr/fcorro-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalslabdeterr/fcorro-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalslabdeterr/fcorro-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalslabdeterr/fcorro-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalslabdeterr/fcorro-condition"]=0;
           }
        } 
        if($key=="typicalslabdeterhoneycomb-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalslabdeterhoneycomb-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalslabdeterhoneycomb-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalslabdeterhoneycomb-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalslabdeterhoneycomb-condition"]=0;
           }
        } 
        // Typical Stair Deterioation
        if($key=="typicalstaircasedetercracks-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalstaircasedetercracks-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalstaircasedetercracks-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalstaircasedetercracks-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalstaircasedetercracks-condition"]=0;
           }
        } 
        if($key=="typicalstaircasedeterscaling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalstaircasedeterscaling-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalstaircasedeterscaling-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalstaircasedeterscaling-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalstaircasedeterscaling-condition"]=0;
           }
        } 
       
        if($key=="typicalstaircasedeterr/fexp-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalstaircasedeterr/fexp-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalstaircasedeterr/fexp-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalstaircasedeterr/fexp-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalstaircasedeterr/fexp-condition"]=0;
           }
        } 
       
        if($key=="typicalstaircasedeterr/fcorro-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalstaircasedeterr/fcorro-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalstaircasedeterr/fcorro-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalstaircasedeterr/fcorro-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalstaircasedeterr/fcorro-condition"]=0;
           }
        } 
        if($key=="typicalstaircasedeterhoneycomb-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalstaircasedeterhoneycomb-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalstaircasedeterhoneycomb-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalstaircasedeterhoneycomb-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalstaircasedeterhoneycomb-condition"]=0;
           }
        } 
        // Typical Stair Deterioation only for steel
        if($key=="steeltypicalstairdeterrusting-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalstairdeterrusting-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalstairdeterrusting-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalstairdeterrusting-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalstairdeterrusting-condition"]=0;
           }
        } 
        if($key=="steeltypicalstairdeterflaking-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalstairdeterflaking-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalstairdeterflaking-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalstairdeterflaking-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalstairdeterflaking-condition"]=0;
           }
        } 
        if($key=="steeltypicalstairdeteryielding-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalstairdeteryielding-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalstairdeteryielding-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalstairdeteryielding-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalstairdeteryielding-condition"]=0;
           }
        } 
        if($key=="steeltypicalstairdeterbuckling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["steeltypicalstairdeterbuckling-condition"]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["steeltypicalstairdeterbuckling-condition"]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["steeltypicalstairdeterbuckling-condition"]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["steeltypicalstairdeterbuckling-condition"]=0;
           }
        } 
        // Typical Coupling Beam Deterioation
        if($key=="typicalcouplingbeamdetercracks-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcouplingbeamdetercracks-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcouplingbeamdetercracks-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcouplingbeamdetercracks-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcouplingbeamdetercracks-condition"]=0;
           }
        } 
       
        if($key=="typicalcouplingbeamdeterscaling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcouplingbeamdeterscaling-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcouplingbeamdeterscaling-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcouplingbeamdeterscaling-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcouplingbeamdeterscaling-condition"]=0;
           }
        } 
       
        if($key=="typicalcouplingbeamdeterr/fexp-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcouplingbeamdeterr/fexp-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcouplingbeamdeterr/fexp-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcouplingbeamdeterr/fexp-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcouplingbeamdeterr/fexp-condition"]=0;
           }
        } 
       
        if($key=="typicalcouplingbeamdeterr/fcorro-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcouplingbeamdeterr/fcorro-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcouplingbeamdeterr/fcorro-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcouplingbeamdeterr/fcorro-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcouplingbeamdeterr/fcorro-condition"]=0;
           }
        } 
       
        if($key=="typicalcouplingbeamdeterhoneycomb-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalcouplingbeamdeterhoneycomb-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalcouplingbeamdeterhoneycomb-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalcouplingbeamdeterhoneycomb-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalcouplingbeamdeterhoneycomb-condition"]=0;
           }
        } 
        // Typical Shear wall Deterioation
       
        if($key=="typicalshearwalldetercracks-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalshearwalldetercracks-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalshearwalldetercracks-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalshearwalldetercracks-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalshearwalldetercracks-condition"]=0;
           }
        } 
       
        if($key=="typicalshearwalldeterscaling-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalshearwalldeterscaling-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalshearwalldeterscaling-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalshearwalldeterscaling-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalshearwalldeterscaling-condition"]=0;
           }
        } 
       
        if($key=="typicalshearwalldeterr/fexp-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalshearwalldeterr/fexp-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalshearwalldeterr/fexp-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalshearwalldeterr/fexp-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalshearwalldeterr/fexp-condition"]=0;
           }
        } 
       
        if($key=="typicalshearwalldeterr/fcorro-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalshearwalldeterr/fcorro-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalshearwalldeterr/fcorro-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalshearwalldeterr/fcorro-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalshearwalldeterr/fcorro-condition"]=0;
           }
        } 
        if($key=="typicalshearwalldeterhoneycomb-condition")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf["typicalshearwalldeterhoneycomb-condition"]=4;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf["typicalshearwalldeterhoneycomb-condition"]=8;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf["typicalshearwalldeterhoneycomb-condition"]=16;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf["typicalshearwalldeterhoneycomb-condition"]=0;
           }
        } 
       

    }



$sum= 0;
foreach ($b_smrf as $number){
  $sum += $number;
}
echo $sum."==this is the sum------";
print_r($b_smrf);
echo "<br> <br>";
}
}

?>

     <!-- 
        table not present in db
        transfer to shear wall table


      -->

<!-- if($key=="")
        {
            if(strtolower($value)=="yes"){
                $b_smrf[""]=;
            }else{
                $b_smrf[""]=;
            }
        }
        if($key=="")
        {
           if(strtolower($value=='poor'))
           {
               $b_smrf[""]=;
           }
           elseif(strtolower($value=='average'))
           {
               $b_smrf[""]=;
           }
           elseif(strtolower($value=='good'))
           {
               $b_smrf[""]=;
           }
        } 
    -->

    <!-- 
        if($key=="")
        {
           if(strtolower($value=='minor'))
           {
               $b_smrf[""]=2;
           }
           elseif(strtolower($value=='moderate'))
           {
               $b_smrf[""]=4;
           }
           elseif(strtolower($value=='severe'))
           {
               $b_smrf[""]=8;
           }
           elseif(strtoupper($value=='NA'))
           {
              $b_smrf[""]=0;
           }
        } 
       
     -->
